<?php
/**
 * Editorial glossary for the offline translator: Spanish → English, French, Italian.
 *
 * This is the vocabulary the site translates with, so it is meant to be read and edited
 * by a person. Every entry is explicit for each target language, including the gender
 * variants, because the engine copies the source capitalisation and does not inflect:
 * a missing variant turns a complete phrase into a partial one, and a partial one is
 * never published.
 *
 * Keys are normalised on load, so accents and case never matter: `Espontánea`,
 * `espontanea` and `espontánea` all resolve to the same entry.
 *
 * A site can extend this without touching code through the `pvc_lt_glossary` option:
 *   array('mi palabra' => array('en' => '...', 'fr' => '...', 'it' => '...'))
 */
if (!defined('ABSPATH')) { exit; }

function pvc_lt_offline_base_dictionary(): array {
    return array_merge(
        pvc_lt_offline_people(),
        pvc_lt_offline_character(),
        pvc_lt_offline_appearance(),
        pvc_lt_offline_origins(),
        pvc_lt_offline_services(),
        pvc_lt_offline_places(),
        pvc_lt_offline_feelings(),
        pvc_lt_offline_common(),
        pvc_lt_offline_languages()
    );
}

/** People. */
function pvc_lt_offline_people(): array {
    return array(
        'chica' => array('en' => 'girl', 'fr' => 'fille', 'it' => 'ragazza'),
        'chico' => array('en' => 'boy', 'fr' => 'garçon', 'it' => 'ragazzo'),
        'mujer' => array('en' => 'woman', 'fr' => 'femme', 'it' => 'donna'),
        'hombre' => array('en' => 'man', 'fr' => 'homme', 'it' => 'uomo'),
        'señora' => array('en' => 'lady', 'fr' => 'dame', 'it' => 'signora'),
        'señor' => array('en' => 'gentleman', 'fr' => 'monsieur', 'it' => 'signore'),
        'modelo' => array('en' => 'model', 'fr' => 'modèle', 'it' => 'modella'),
        'compañera' => array('en' => 'companion', 'fr' => 'compagne', 'it' => 'compagna'),
        'amiga' => array('en' => 'friend', 'fr' => 'amie', 'it' => 'amica'),
        'clienta' => array('en' => 'client', 'fr' => 'cliente', 'it' => 'cliente'),
        'cliente' => array('en' => 'client', 'fr' => 'client', 'it' => 'cliente'),
        'caballero' => array('en' => 'gentleman', 'fr' => 'gentleman', 'it' => 'gentiluomo'),
        'persona' => array('en' => 'person', 'fr' => 'personne', 'it' => 'persona'),
    );
}

/** Character and personality. */
function pvc_lt_offline_character(): array {
    return array(
        'amable' => array('en' => 'kind', 'fr' => 'aimable', 'it' => 'gentile'),
        'carismática' => array('en' => 'charismatic', 'fr' => 'charismatique', 'it' => 'carismatica'),
        'carismático' => array('en' => 'charismatic', 'fr' => 'charismatique', 'it' => 'carismatico'),
        'griega' => array('en' => 'greek', 'fr' => 'grecque', 'it' => 'greca'),
        'agradable' => array('en' => 'pleasant', 'fr' => 'agréable', 'it' => 'piacevole'),
        'simpática' => array('en' => 'friendly', 'fr' => 'sympathique', 'it' => 'simpatica'),
        'simpático' => array('en' => 'friendly', 'fr' => 'sympathique', 'it' => 'simpatico'),
        'cariñosa' => array('en' => 'affectionate', 'fr' => 'affectueuse', 'it' => 'affettuosa'),
        'cariñoso' => array('en' => 'affectionate', 'fr' => 'affectueux', 'it' => 'affettuoso'),
        'dulce' => array('en' => 'sweet', 'fr' => 'douce', 'it' => 'dolce'),
        'tierna' => array('en' => 'tender', 'fr' => 'tendre', 'it' => 'dolce'),
        'tierno' => array('en' => 'tender', 'fr' => 'tendre', 'it' => 'tenero'),
        'apasionada' => array('en' => 'passionate', 'fr' => 'passionnée', 'it' => 'appassionata'),
        'apasionado' => array('en' => 'passionate', 'fr' => 'passionné', 'it' => 'appassionato'),
        'divertida' => array('en' => 'fun', 'fr' => 'amusante', 'it' => 'divertente'),
        'divertido' => array('en' => 'fun', 'fr' => 'amusant', 'it' => 'divertente'),
        'alegre' => array('en' => 'cheerful', 'fr' => 'joyeuse', 'it' => 'allegra'),
        'risueña' => array('en' => 'smiling', 'fr' => 'souriante', 'it' => 'sorridente'),
        'risueño' => array('en' => 'smiling', 'fr' => 'souriant', 'it' => 'sorridente'),
        'sonriente' => array('en' => 'smiling', 'fr' => 'souriante', 'it' => 'sorridente'),
        'extrovertida' => array('en' => 'extroverted', 'fr' => 'extravertie', 'it' => 'estroversa'),
        'extrovertido' => array('en' => 'extroverted', 'fr' => 'extraverti', 'it' => 'estroverso'),
        'introvertida' => array('en' => 'introverted', 'fr' => 'introvertie', 'it' => 'introversa'),
        'tímida' => array('en' => 'shy', 'fr' => 'timide', 'it' => 'timida'),
        'tímido' => array('en' => 'shy', 'fr' => 'timide', 'it' => 'timido'),
        'reservada' => array('en' => 'reserved', 'fr' => 'réservée', 'it' => 'riservata'),
        'reservado' => array('en' => 'reserved', 'fr' => 'réservé', 'it' => 'riservato'),
        'discreta' => array('en' => 'discreet', 'fr' => 'discrète', 'it' => 'discreta'),
        'discreto' => array('en' => 'discreet', 'fr' => 'discret', 'it' => 'discreto'),
        'elegante' => array('en' => 'elegant', 'fr' => 'élégante', 'it' => 'elegante'),
        'sofisticada' => array('en' => 'sophisticated', 'fr' => 'sophistiquée', 'it' => 'sofisticata'),
        'sofisticado' => array('en' => 'sophisticated', 'fr' => 'sophistiqué', 'it' => 'sofisticato'),
        'natural' => array('en' => 'natural', 'fr' => 'naturelle', 'it' => 'naturale'),
        'espontánea' => array('en' => 'spontaneous', 'fr' => 'spontanée', 'it' => 'spontanea'),
        'espontáneo' => array('en' => 'spontaneous', 'fr' => 'spontané', 'it' => 'spontaneo'),
        'auténtica' => array('en' => 'authentic', 'fr' => 'authentique', 'it' => 'autentica'),
        'auténtico' => array('en' => 'authentic', 'fr' => 'authentique', 'it' => 'autentico'),
        'sincera' => array('en' => 'sincere', 'fr' => 'sincère', 'it' => 'sincera'),
        'sincero' => array('en' => 'sincere', 'fr' => 'sincère', 'it' => 'sincero'),
        'honesta' => array('en' => 'honest', 'fr' => 'honnête', 'it' => 'onesta'),
        'honesto' => array('en' => 'honest', 'fr' => 'honnête', 'it' => 'onesto'),
        'inteligente' => array('en' => 'intelligent', 'fr' => 'intelligente', 'it' => 'intelligente'),
        'culta' => array('en' => 'cultured', 'fr' => 'cultivée', 'it' => 'colta'),
        'culto' => array('en' => 'cultured', 'fr' => 'cultivé', 'it' => 'colto'),
        'educada' => array('en' => 'polite', 'fr' => 'polie', 'it' => 'educata'),
        'educado' => array('en' => 'polite', 'fr' => 'poli', 'it' => 'educato'),
        'atenta' => array('en' => 'attentive', 'fr' => 'attentionnée', 'it' => 'premurosa'),
        'atento' => array('en' => 'attentive', 'fr' => 'attentionné', 'it' => 'premuroso'),
        'generosa' => array('en' => 'generous', 'fr' => 'généreuse', 'it' => 'generosa'),
        'generoso' => array('en' => 'generous', 'fr' => 'généreux', 'it' => 'generoso'),
        'tranquila' => array('en' => 'calm', 'fr' => 'tranquille', 'it' => 'tranquilla'),
        'tranquilo' => array('en' => 'calm', 'fr' => 'tranquille', 'it' => 'tranquillo'),
        'serena' => array('en' => 'serene', 'fr' => 'sereine', 'it' => 'serena'),
        'sereno' => array('en' => 'serene', 'fr' => 'serein', 'it' => 'sereno'),
        'paciente' => array('en' => 'patient', 'fr' => 'patiente', 'it' => 'paziente'),
        'sensible' => array('en' => 'sensitive', 'fr' => 'sensible', 'it' => 'sensibile'),
        'activa' => array('en' => 'active', 'fr' => 'active', 'it' => 'attiva'),
        'activo' => array('en' => 'active', 'fr' => 'actif', 'it' => 'attivo'),
        'deportista' => array('en' => 'sporty', 'fr' => 'sportive', 'it' => 'sportiva'),
        'viajera' => array('en' => 'well-travelled', 'fr' => 'voyageuse', 'it' => 'viaggiatrice'),
        'viajero' => array('en' => 'well-travelled', 'fr' => 'voyageur', 'it' => 'viaggiatore'),
        'curiosa' => array('en' => 'curious', 'fr' => 'curieuse', 'it' => 'curiosa'),
        'curioso' => array('en' => 'curious', 'fr' => 'curieux', 'it' => 'curioso'),
        'creativa' => array('en' => 'creative', 'fr' => 'créative', 'it' => 'creativa'),
        'creativo' => array('en' => 'creative', 'fr' => 'créatif', 'it' => 'creativo'),
        'trabajadora' => array('en' => 'hard-working', 'fr' => 'travailleuse', 'it' => 'laboriosa'),
        'trabajador' => array('en' => 'hard-working', 'fr' => 'travailleur', 'it' => 'laborioso'),
        'emprendedora' => array('en' => 'enterprising', 'fr' => 'entreprenante', 'it' => 'intraprendente'),
        'independiente' => array('en' => 'independent', 'fr' => 'indépendante', 'it' => 'indipendente'),
        'libre' => array('en' => 'free', 'fr' => 'libre', 'it' => 'libera'),
        'romántica' => array('en' => 'romantic', 'fr' => 'romantique', 'it' => 'romantica'),
        'romántico' => array('en' => 'romantic', 'fr' => 'romantique', 'it' => 'romantico'),
        'enigmática' => array('en' => 'enigmatic', 'fr' => 'énigmatique', 'it' => 'enigmatica'),
        'enigmático' => array('en' => 'enigmatic', 'fr' => 'énigmatique', 'it' => 'enigmatico'),
        'encantadora' => array('en' => 'charming', 'fr' => 'charmante', 'it' => 'incantevole'),
        'encantador' => array('en' => 'charming', 'fr' => 'charmant', 'it' => 'incantevole'),
        'adorable' => array('en' => 'adorable', 'fr' => 'adorable', 'it' => 'adorabile'),
        'traviesa' => array('en' => 'mischievous', 'fr' => 'espiègle', 'it' => 'birichina'),
        'travieso' => array('en' => 'mischievous', 'fr' => 'espiègle', 'it' => 'birichino'),
        'atrevida' => array('en' => 'daring', 'fr' => 'audacieuse', 'it' => 'audace'),
        'atrevido' => array('en' => 'daring', 'fr' => 'audacieux', 'it' => 'audace'),
        'juguetona' => array('en' => 'playful', 'fr' => 'joueuse', 'it' => 'giocosa'),
        'juguetón' => array('en' => 'playful', 'fr' => 'joueur', 'it' => 'giocoso'),
        'coqueta' => array('en' => 'flirtatious', 'fr' => 'coquette', 'it' => 'civettuola'),
        'coqueto' => array('en' => 'flirtatious', 'fr' => 'coquet', 'it' => 'civettuolo'),
        'seductora' => array('en' => 'seductive', 'fr' => 'séductrice', 'it' => 'seduttrice'),
        'seductor' => array('en' => 'seductive', 'fr' => 'séducteur', 'it' => 'seduttore'),
        'magnífica' => array('en' => 'magnificent', 'fr' => 'magnifique', 'it' => 'magnifica'),
        'magnífico' => array('en' => 'magnificent', 'fr' => 'magnifique', 'it' => 'magnifico'),
        'espectacular' => array('en' => 'spectacular', 'fr' => 'spectaculaire', 'it' => 'spettacolare'),
        'profesional' => array('en' => 'professional', 'fr' => 'professionnelle', 'it' => 'professionale'),
        'puntual' => array('en' => 'punctual', 'fr' => 'ponctuelle', 'it' => 'puntuale'),
        'limpia' => array('en' => 'clean', 'fr' => 'propre', 'it' => 'pulita'),
        'limpio' => array('en' => 'clean', 'fr' => 'propre', 'it' => 'pulito'),
        'madura' => array('en' => 'mature', 'fr' => 'mûre', 'it' => 'matura'),
        'maduro' => array('en' => 'mature', 'fr' => 'mûr', 'it' => 'maturo'),
        'joven' => array('en' => 'young', 'fr' => 'jeune', 'it' => 'giovane'),
        'juvenil' => array('en' => 'youthful', 'fr' => 'juvénile', 'it' => 'giovanile'),
        'femenina' => array('en' => 'feminine', 'fr' => 'féminine', 'it' => 'femminile'),
        'femenino' => array('en' => 'feminine', 'fr' => 'féminin', 'it' => 'femminile'),
        'masculina' => array('en' => 'masculine', 'fr' => 'masculine', 'it' => 'maschile'),
        'picante' => array('en' => 'spicy', 'fr' => 'épicée', 'it' => 'piccante'),
        'ardiente' => array('en' => 'fiery', 'fr' => 'ardente', 'it' => 'ardente'),
        'pasional' => array('en' => 'passionate', 'fr' => 'passionnelle', 'it' => 'passionale'),
    );
}

/** Physical appearance and features. */
function pvc_lt_offline_appearance(): array {
    return array(
        'alta' => array('en' => 'tall', 'fr' => 'grande', 'it' => 'alta'),
        'alto' => array('en' => 'tall', 'fr' => 'grand', 'it' => 'alto'),
        'baja' => array('en' => 'short', 'fr' => 'petite', 'it' => 'bassa'),
        'bajo' => array('en' => 'short', 'fr' => 'petit', 'it' => 'basso'),
        'delgada' => array('en' => 'slim', 'fr' => 'mince', 'it' => 'snella'),
        'delgado' => array('en' => 'slim', 'fr' => 'mince', 'it' => 'snello'),
        'esbelta' => array('en' => 'slender', 'fr' => 'svelte', 'it' => 'slanciata'),
        'esbelto' => array('en' => 'slender', 'fr' => 'svelte', 'it' => 'slanciato'),
        'curvilínea' => array('en' => 'curvaceous', 'fr' => 'pulpeuse', 'it' => 'formosa'),
        'fibrosa' => array('en' => 'toned', 'fr' => 'tonique', 'it' => 'tonica'),
        'atlética' => array('en' => 'athletic', 'fr' => 'athlétique', 'it' => 'atletica'),
        'voluptuosa' => array('en' => 'voluptuous', 'fr' => 'voluptueuse', 'it' => 'voluttuosa'),
        'voluptuoso' => array('en' => 'voluptuous', 'fr' => 'voluptueux', 'it' => 'voluttuoso'),
        'morena' => array('en' => 'brunette', 'fr' => 'brune', 'it' => 'bruna'),
        'moreno' => array('en' => 'brunette', 'fr' => 'brun', 'it' => 'bruno'),
        'rubia' => array('en' => 'blonde', 'fr' => 'blonde', 'it' => 'bionda'),
        'rubio' => array('en' => 'blonde', 'fr' => 'blond', 'it' => 'biondo'),
        'pelirroja' => array('en' => 'red-haired', 'fr' => 'rousse', 'it' => 'rossa'),
        'pelirrojo' => array('en' => 'red-haired', 'fr' => 'roux', 'it' => 'rosso'),
        'castaña' => array('en' => 'brunette', 'fr' => 'châtain', 'it' => 'castana'),
        'guapa' => array('en' => 'beautiful', 'fr' => 'belle', 'it' => 'bella'),
        'guapo' => array('en' => 'handsome', 'fr' => 'beau', 'it' => 'bello'),
        'bella' => array('en' => 'beautiful', 'fr' => 'belle', 'it' => 'bella'),
        'bello' => array('en' => 'beautiful', 'fr' => 'beau', 'it' => 'bello'),
        'hermosa' => array('en' => 'beautiful', 'fr' => 'magnifique', 'it' => 'bellissima'),
        'hermoso' => array('en' => 'beautiful', 'fr' => 'magnifique', 'it' => 'bellissimo'),
        'preciosa' => array('en' => 'gorgeous', 'fr' => 'magnifique', 'it' => 'bellissima'),
        'precioso' => array('en' => 'gorgeous', 'fr' => 'magnifique', 'it' => 'bellissimo'),
        'atractiva' => array('en' => 'attractive', 'fr' => 'attrayante', 'it' => 'attraente'),
        'atractivo' => array('en' => 'attractive', 'fr' => 'attrayant', 'it' => 'attraente'),
        'despampanante' => array('en' => 'stunning', 'fr' => 'éblouissante', 'it' => 'sbalorditiva'),
        'sensual' => array('en' => 'sensual', 'fr' => 'sensuelle', 'it' => 'sensuale'),
        'sexy' => array('en' => 'sexy', 'fr' => 'sexy', 'it' => 'sexy'),
        'estilosa' => array('en' => 'stylish', 'fr' => 'stylée', 'it' => 'stilosa'),
        'estiloso' => array('en' => 'stylish', 'fr' => 'stylé', 'it' => 'stiloso'),
        'refinada' => array('en' => 'refined', 'fr' => 'raffinée', 'it' => 'raffinata'),
        'refinado' => array('en' => 'refined', 'fr' => 'raffiné', 'it' => 'raffinato'),
        'arreglada' => array('en' => 'well-groomed', 'fr' => 'soignée', 'it' => 'curata'),
        'arreglado' => array('en' => 'well-groomed', 'fr' => 'soigné', 'it' => 'curato'),
        'ojos' => array('en' => 'eyes', 'fr' => 'yeux', 'it' => 'occhi'),
        'ojos claros' => array('en' => 'light eyes', 'fr' => 'yeux clairs', 'it' => 'occhi chiari'),
        'ojos oscuros' => array('en' => 'dark eyes', 'fr' => 'yeux foncés', 'it' => 'occhi scuri'),
        // The whole description, because a bare "de" would resolve to something that reads
        // wrong in French and Italian even though every word would count as translated.
        'de ojos claros' => array('en' => 'with light eyes', 'fr' => 'aux yeux clairs', 'it' => 'con occhi chiari'),
        'de ojos oscuros' => array('en' => 'with dark eyes', 'fr' => 'aux yeux foncés', 'it' => 'con occhi scuri'),
        'de piel clara' => array('en' => 'with fair skin', 'fr' => 'à la peau claire', 'it' => 'dalla pelle chiara'),
        'de piel morena' => array('en' => 'with tanned skin', 'fr' => 'au teint mat', 'it' => 'dalla pelle ambrata'),
        'de pelo largo' => array('en' => 'with long hair', 'fr' => 'aux cheveux longs', 'it' => 'con i capelli lunghi'),
        'de pelo corto' => array('en' => 'with short hair', 'fr' => 'aux cheveux courts', 'it' => 'con i capelli corti'),
        'mirada' => array('en' => 'gaze', 'fr' => 'regard', 'it' => 'sguardo'),
        'sonrisa' => array('en' => 'smile', 'fr' => 'sourire', 'it' => 'sorriso'),
        'risa' => array('en' => 'laughter', 'fr' => 'rire', 'it' => 'risata'),
        'voz' => array('en' => 'voice', 'fr' => 'voix', 'it' => 'voce'),
        'labios' => array('en' => 'lips', 'fr' => 'lèvres', 'it' => 'labbra'),
        'piel' => array('en' => 'skin', 'fr' => 'peau', 'it' => 'pelle'),
        'piel morena' => array('en' => 'tanned skin', 'fr' => 'peau mate', 'it' => 'pelle ambrata'),
        'piel clara' => array('en' => 'fair skin', 'fr' => 'peau claire', 'it' => 'pelle chiara'),
        'cabello' => array('en' => 'hair', 'fr' => 'cheveux', 'it' => 'capelli'),
        'pelo largo' => array('en' => 'long hair', 'fr' => 'cheveux longs', 'it' => 'capelli lunghi'),
        'pelo corto' => array('en' => 'short hair', 'fr' => 'cheveux courts', 'it' => 'capelli corti'),
        'cuerpo' => array('en' => 'body', 'fr' => 'corps', 'it' => 'corpo'),
        'figura' => array('en' => 'figure', 'fr' => 'silhouette', 'it' => 'figura'),
        'curvas' => array('en' => 'curves', 'fr' => 'courbes', 'it' => 'curve'),
        'piernas' => array('en' => 'legs', 'fr' => 'jambes', 'it' => 'gambe'),
        'manos' => array('en' => 'hands', 'fr' => 'mains', 'it' => 'mani'),
        'tatuajes' => array('en' => 'tattoos', 'fr' => 'tatouages', 'it' => 'tatuaggi'),
        'altura' => array('en' => 'height', 'fr' => 'taille', 'it' => 'altezza'),
        'medidas' => array('en' => 'measurements', 'fr' => 'mensurations', 'it' => 'misure'),
        'cintura' => array('en' => 'waist', 'fr' => 'taille', 'it' => 'vita'),
        'caderas' => array('en' => 'hips', 'fr' => 'hanches', 'it' => 'fianchi'),
        'perfume' => array('en' => 'perfume', 'fr' => 'parfum', 'it' => 'profumo'),
        'aroma' => array('en' => 'scent', 'fr' => 'parfum', 'it' => 'profumo'),
    );
}

/** Origin and nationality. */
function pvc_lt_offline_origins(): array {
    return array(
        'española' => array('en' => 'spanish', 'fr' => 'espagnole', 'it' => 'spagnola'),
        'latina' => array('en' => 'latin', 'fr' => 'latine', 'it' => 'latina'),
        'latino' => array('en' => 'latin', 'fr' => 'latin', 'it' => 'latino'),
        'brasileña' => array('en' => 'brazilian', 'fr' => 'brésilienne', 'it' => 'brasiliana'),
        'brasileño' => array('en' => 'brazilian', 'fr' => 'brésilien', 'it' => 'brasiliano'),
        'colombiana' => array('en' => 'colombian', 'fr' => 'colombienne', 'it' => 'colombiana'),
        'colombiano' => array('en' => 'colombian', 'fr' => 'colombien', 'it' => 'colombiano'),
        'venezolana' => array('en' => 'venezuelan', 'fr' => 'vénézuélienne', 'it' => 'venezuelana'),
        'venezolano' => array('en' => 'venezuelan', 'fr' => 'vénézuélien', 'it' => 'venezuelano'),
        'argentina' => array('en' => 'argentinian', 'fr' => 'argentine', 'it' => 'argentina'),
        'argentino' => array('en' => 'argentinian', 'fr' => 'argentin', 'it' => 'argentino'),
        'mexicana' => array('en' => 'mexican', 'fr' => 'mexicaine', 'it' => 'messicana'),
        'mexicano' => array('en' => 'mexican', 'fr' => 'mexicain', 'it' => 'messicano'),
        'cubana' => array('en' => 'cuban', 'fr' => 'cubaine', 'it' => 'cubana'),
        'cubano' => array('en' => 'cuban', 'fr' => 'cubain', 'it' => 'cubano'),
        'dominicana' => array('en' => 'dominican', 'fr' => 'dominicaine', 'it' => 'dominicana'),
        'dominicano' => array('en' => 'dominican', 'fr' => 'dominicain', 'it' => 'dominicano'),
        'peruana' => array('en' => 'peruvian', 'fr' => 'péruvienne', 'it' => 'peruviana'),
        'peruano' => array('en' => 'peruvian', 'fr' => 'péruvien', 'it' => 'peruviano'),
        'ecuatoriana' => array('en' => 'ecuadorian', 'fr' => 'équatorienne', 'it' => 'ecuadoriana'),
        'chilena' => array('en' => 'chilean', 'fr' => 'chilienne', 'it' => 'cilena'),
        'chileno' => array('en' => 'chilean', 'fr' => 'chilien', 'it' => 'cileno'),
        'uruguaya' => array('en' => 'uruguayan', 'fr' => 'uruguayenne', 'it' => 'uruguaiana'),
        'paraguaya' => array('en' => 'paraguayan', 'fr' => 'paraguayenne', 'it' => 'paraguaiana'),
        'boliviana' => array('en' => 'bolivian', 'fr' => 'bolivienne', 'it' => 'boliviana'),
        'panameña' => array('en' => 'panamanian', 'fr' => 'panaméenne', 'it' => 'panamense'),
        'costarricense' => array('en' => 'costa rican', 'fr' => 'costaricienne', 'it' => 'costaricana'),
        'hondureña' => array('en' => 'honduran', 'fr' => 'hondurienne', 'it' => 'honduregna'),
        'guatemalteca' => array('en' => 'guatemalan', 'fr' => 'guatémaltèque', 'it' => 'guatemalteca'),
        'salvadoreña' => array('en' => 'salvadoran', 'fr' => 'salvadorienne', 'it' => 'salvadoregna'),
        'nicaragüense' => array('en' => 'nicaraguan', 'fr' => 'nicaraguayenne', 'it' => 'nicaraguense'),
        'puertorriqueña' => array('en' => 'puerto rican', 'fr' => 'portoricaine', 'it' => 'portoricana'),
        'italiana' => array('en' => 'italian', 'fr' => 'italienne', 'it' => 'italiana'),
        'italiano' => array('en' => 'italian', 'fr' => 'italien', 'it' => 'italiano'),
        'francesa' => array('en' => 'french', 'fr' => 'française', 'it' => 'francese'),
        'alemana' => array('en' => 'german', 'fr' => 'allemande', 'it' => 'tedesca'),
        'portuguesa' => array('en' => 'portuguese', 'fr' => 'portugaise', 'it' => 'portoghese'),
        'rumana' => array('en' => 'romanian', 'fr' => 'roumaine', 'it' => 'rumena'),
        'rusa' => array('en' => 'russian', 'fr' => 'russe', 'it' => 'russa'),
        'ucraniana' => array('en' => 'ukrainian', 'fr' => 'ukrainienne', 'it' => 'ucraina'),
        'polaca' => array('en' => 'polish', 'fr' => 'polonaise', 'it' => 'polacca'),
        'marroquí' => array('en' => 'moroccan', 'fr' => 'marocaine', 'it' => 'marocchina'),
        'argelina' => array('en' => 'algerian', 'fr' => 'algérienne', 'it' => 'algerina'),
        'nigeriana' => array('en' => 'nigerian', 'fr' => 'nigériane', 'it' => 'nigeriana'),
        'senegalesa' => array('en' => 'senegalese', 'fr' => 'sénégalaise', 'it' => 'senegalese'),
        'china' => array('en' => 'chinese', 'fr' => 'chinoise', 'it' => 'cinese'),
        'japonesa' => array('en' => 'japanese', 'fr' => 'japonaise', 'it' => 'giapponese'),
        'tailandesa' => array('en' => 'thai', 'fr' => 'thaïlandaise', 'it' => 'thailandese'),
        'filipina' => array('en' => 'filipino', 'fr' => 'philippine', 'it' => 'filippina'),
        'árabe' => array('en' => 'arabic', 'fr' => 'arabe', 'it' => 'araba'),
        'catalana' => array('en' => 'catalan', 'fr' => 'catalane', 'it' => 'catalana'),
        'andaluza' => array('en' => 'andalusian', 'fr' => 'andalouse', 'it' => 'andalusa'),
        'madrileña' => array('en' => 'from madrid', 'fr' => 'madrilène', 'it' => 'madrilena'),
        'barcelonesa' => array('en' => 'from barcelona', 'fr' => 'barcelonaise', 'it' => 'barcellonese'),
        'valenciana' => array('en' => 'valencian', 'fr' => 'valencienne', 'it' => 'valenciana'),
        'sevillana' => array('en' => 'from seville', 'fr' => 'sévillane', 'it' => 'sivigliana'),
    );
}

/** Services, encounters and the business vocabulary around them. */
function pvc_lt_offline_services(): array {
    return array(
        'acompañamiento' => array('en' => 'companionship', 'fr' => 'accompagnement', 'it' => 'accompagnamento'),
        'compañía' => array('en' => 'company', 'fr' => 'compagnie', 'it' => 'compagnia'),
        'cita' => array('en' => 'date', 'fr' => 'rendez-vous', 'it' => 'appuntamento'),
        'encuentro' => array('en' => 'encounter', 'fr' => 'rencontre', 'it' => 'incontro'),
        'reserva' => array('en' => 'booking', 'fr' => 'réservation', 'it' => 'prenotazione'),
        'disponibilidad' => array('en' => 'availability', 'fr' => 'disponibilité', 'it' => 'disponibilità'),
        'disponibilidad inmediata' => array('en' => 'immediate availability', 'fr' => 'disponibilité immédiate', 'it' => 'disponibilità immediata'),
        'servicio' => array('en' => 'service', 'fr' => 'service', 'it' => 'servizio'),
        'servicios' => array('en' => 'services', 'fr' => 'services', 'it' => 'servizi'),
        'tarifa' => array('en' => 'rate', 'fr' => 'tarif', 'it' => 'tariffa'),
        'precio' => array('en' => 'price', 'fr' => 'prix', 'it' => 'prezzo'),
        'hora' => array('en' => 'hour', 'fr' => 'heure', 'it' => 'ora'),
        'media hora' => array('en' => 'half an hour', 'fr' => 'demi-heure', 'it' => 'mezz’ora'),
        'dos horas' => array('en' => 'two hours', 'fr' => 'deux heures', 'it' => 'due ore'),
        'noche' => array('en' => 'night', 'fr' => 'nuit', 'it' => 'notte'),
        'día' => array('en' => 'day', 'fr' => 'jour', 'it' => 'giorno'),
        'tarde' => array('en' => 'afternoon', 'fr' => 'après-midi', 'it' => 'pomeriggio'),
        'fin de semana' => array('en' => 'weekend', 'fr' => 'week-end', 'it' => 'fine settimana'),
        'viaje' => array('en' => 'trip', 'fr' => 'voyage', 'it' => 'viaggio'),
        'desplazamiento' => array('en' => 'travel', 'fr' => 'déplacement', 'it' => 'spostamento'),
        'masaje' => array('en' => 'massage', 'fr' => 'massage', 'it' => 'massaggio'),
        'masaje relajante' => array('en' => 'relaxing massage', 'fr' => 'massage relaxant', 'it' => 'massaggio rilassante'),
        'masaje tailandés' => array('en' => 'thai massage', 'fr' => 'massage thaïlandais', 'it' => 'massaggio thailandese'),
        'masaje tántrico' => array('en' => 'tantric massage', 'fr' => 'massage tantrique', 'it' => 'massaggio tantrico'),
        'masaje erótico' => array('en' => 'erotic massage', 'fr' => 'massage érotique', 'it' => 'massaggio erotico'),
        'ducha' => array('en' => 'shower', 'fr' => 'douche', 'it' => 'doccia'),
        'baño' => array('en' => 'bath', 'fr' => 'bain', 'it' => 'bagno'),
        'cena' => array('en' => 'dinner', 'fr' => 'dîner', 'it' => 'cena'),
        'comida' => array('en' => 'lunch', 'fr' => 'déjeuner', 'it' => 'pranzo'),
        'copa' => array('en' => 'drink', 'fr' => 'verre', 'it' => 'drink'),
        'champán' => array('en' => 'champagne', 'fr' => 'champagne', 'it' => 'champagne'),
        'vino' => array('en' => 'wine', 'fr' => 'vin', 'it' => 'vino'),
        'regalo' => array('en' => 'gift', 'fr' => 'cadeau', 'it' => 'regalo'),
        'sorpresa' => array('en' => 'surprise', 'fr' => 'surprise', 'it' => 'sorpresa'),
        'fantasía' => array('en' => 'fantasy', 'fr' => 'fantasme', 'it' => 'fantasia'),
        'deseo' => array('en' => 'desire', 'fr' => 'désir', 'it' => 'desiderio'),
        'placer' => array('en' => 'pleasure', 'fr' => 'plaisir', 'it' => 'piacere'),
        'pasión' => array('en' => 'passion', 'fr' => 'passion', 'it' => 'passione'),
        'juego' => array('en' => 'play', 'fr' => 'jeu', 'it' => 'gioco'),
        'pareja' => array('en' => 'couple', 'fr' => 'couple', 'it' => 'coppia'),
        'trío' => array('en' => 'threesome', 'fr' => 'plan à trois', 'it' => 'triangolo'),
        'soltera' => array('en' => 'single', 'fr' => 'célibataire', 'it' => 'single'),
        'soltero' => array('en' => 'single', 'fr' => 'célibataire', 'it' => 'single'),
        'discreción' => array('en' => 'discretion', 'fr' => 'discrétion', 'it' => 'discrezione'),
        'confidencialidad' => array('en' => 'confidentiality', 'fr' => 'confidentialité', 'it' => 'riservatezza'),
        'privacidad' => array('en' => 'privacy', 'fr' => 'vie privée', 'it' => 'privacy'),
        'seguridad' => array('en' => 'safety', 'fr' => 'sécurité', 'it' => 'sicurezza'),
        'higiene' => array('en' => 'hygiene', 'fr' => 'hygiène', 'it' => 'igiene'),
        'atención' => array('en' => 'attention', 'fr' => 'attention', 'it' => 'attenzione'),
        'trato' => array('en' => 'treatment', 'fr' => 'traitement', 'it' => 'trattamento'),
        'experiencia' => array('en' => 'experience', 'fr' => 'expérience', 'it' => 'esperienza'),
        'calidad' => array('en' => 'quality', 'fr' => 'qualité', 'it' => 'qualità'),
        'exclusividad' => array('en' => 'exclusivity', 'fr' => 'exclusivité', 'it' => 'esclusività'),
        'lujo' => array('en' => 'luxury', 'fr' => 'luxe', 'it' => 'lusso'),
        'premium' => array('en' => 'premium', 'fr' => 'premium', 'it' => 'premium'),
        'elegancia' => array('en' => 'elegance', 'fr' => 'élégance', 'it' => 'eleganza'),
        'belleza' => array('en' => 'beauty', 'fr' => 'beauté', 'it' => 'bellezza'),
        'estilo' => array('en' => 'style', 'fr' => 'style', 'it' => 'stile'),
        'presencia' => array('en' => 'presence', 'fr' => 'présence', 'it' => 'presenza'),
        'encanto' => array('en' => 'charm', 'fr' => 'charme', 'it' => 'fascino'),
        'misterio' => array('en' => 'mystery', 'fr' => 'mystère', 'it' => 'mistero'),
        'energía' => array('en' => 'energy', 'fr' => 'énergie', 'it' => 'energia'),
        'química' => array('en' => 'chemistry', 'fr' => 'alchimie', 'it' => 'chimica'),
        'conexión' => array('en' => 'connection', 'fr' => 'connexion', 'it' => 'connessione'),
        'complicidad' => array('en' => 'rapport', 'fr' => 'complicité', 'it' => 'complicità'),
        'ternura' => array('en' => 'tenderness', 'fr' => 'tendresse', 'it' => 'tenerezza'),
        'dulzura' => array('en' => 'sweetness', 'fr' => 'douceur', 'it' => 'dolcezza'),
        'sinceridad' => array('en' => 'sincerity', 'fr' => 'sincérité', 'it' => 'sincerità'),
        'inteligencia' => array('en' => 'intelligence', 'fr' => 'intelligence', 'it' => 'intelligenza'),
        'cultura' => array('en' => 'culture', 'fr' => 'culture', 'it' => 'cultura'),
        'conversación' => array('en' => 'conversation', 'fr' => 'conversation', 'it' => 'conversazione'),
        'charla' => array('en' => 'chat', 'fr' => 'discussion', 'it' => 'chiacchierata'),
        'simpatía' => array('en' => 'friendliness', 'fr' => 'sympathie', 'it' => 'simpatia'),
        'beso' => array('en' => 'kiss', 'fr' => 'baiser', 'it' => 'bacio'),
        'abrazo' => array('en' => 'hug', 'fr' => 'câlin', 'it' => 'abbraccio'),
        'caricia' => array('en' => 'caress', 'fr' => 'caresse', 'it' => 'carezza'),
    );
}

/** Places and logistics. */
function pvc_lt_offline_places(): array {
    return array(
        'domicilio' => array('en' => 'home', 'fr' => 'domicile', 'it' => 'domicilio'),
        'hotel' => array('en' => 'hotel', 'fr' => 'hôtel', 'it' => 'hotel'),
        'apartamento' => array('en' => 'apartment', 'fr' => 'appartement', 'it' => 'appartamento'),
        'piso' => array('en' => 'flat', 'fr' => 'appartement', 'it' => 'appartamento'),
        'habitación' => array('en' => 'room', 'fr' => 'chambre', 'it' => 'camera'),
        'suite' => array('en' => 'suite', 'fr' => 'suite', 'it' => 'suite'),
        'lugar' => array('en' => 'place', 'fr' => 'lieu', 'it' => 'luogo'),
        'ciudad' => array('en' => 'city', 'fr' => 'ville', 'it' => 'città'),
        'zona' => array('en' => 'area', 'fr' => 'zone', 'it' => 'zona'),
        'barrio' => array('en' => 'neighbourhood', 'fr' => 'quartier', 'it' => 'quartiere'),
        'centro' => array('en' => 'centre', 'fr' => 'centre', 'it' => 'centro'),
        'centro de la ciudad' => array('en' => 'city centre', 'fr' => 'centre-ville', 'it' => 'centro città'),
        'aeropuerto' => array('en' => 'airport', 'fr' => 'aéroport', 'it' => 'aeroporto'),
        'estación' => array('en' => 'station', 'fr' => 'gare', 'it' => 'stazione'),
        'playa' => array('en' => 'beach', 'fr' => 'plage', 'it' => 'spiaggia'),
        'terraza' => array('en' => 'terrace', 'fr' => 'terrasse', 'it' => 'terrazza'),
        'vistas' => array('en' => 'views', 'fr' => 'vue', 'it' => 'vista'),
        'ambiente' => array('en' => 'atmosphere', 'fr' => 'ambiance', 'it' => 'ambiente'),
        'jardín' => array('en' => 'garden', 'fr' => 'jardin', 'it' => 'giardino'),
        'piscina' => array('en' => 'pool', 'fr' => 'piscine', 'it' => 'piscina'),
        'spa' => array('en' => 'spa', 'fr' => 'spa', 'it' => 'spa'),
        'restaurante' => array('en' => 'restaurant', 'fr' => 'restaurant', 'it' => 'ristorante'),
        'bar' => array('en' => 'bar', 'fr' => 'bar', 'it' => 'bar'),
        'discoteca' => array('en' => 'nightclub', 'fr' => 'discothèque', 'it' => 'discoteca'),
        'evento' => array('en' => 'event', 'fr' => 'événement', 'it' => 'evento'),
        'fiesta' => array('en' => 'party', 'fr' => 'fête', 'it' => 'festa'),
        'boda' => array('en' => 'wedding', 'fr' => 'mariage', 'it' => 'matrimonio'),
        'cumpleaños' => array('en' => 'birthday', 'fr' => 'anniversaire', 'it' => 'compleanno'),
        'despedida' => array('en' => 'farewell party', 'fr' => 'enterrement de vie', 'it' => 'addio al celibato'),
        'cena romántica' => array('en' => 'romantic dinner', 'fr' => 'dîner romantique', 'it' => 'cena romantica'),
        'escapada' => array('en' => 'getaway', 'fr' => 'escapade', 'it' => 'fuga'),
        'vacaciones' => array('en' => 'holidays', 'fr' => 'vacances', 'it' => 'vacanze'),
        'trabajo' => array('en' => 'work', 'fr' => 'travail', 'it' => 'lavoro'),
        'oficina' => array('en' => 'office', 'fr' => 'bureau', 'it' => 'ufficio'),
        'casa' => array('en' => 'house', 'fr' => 'maison', 'it' => 'casa'),
        'hogar' => array('en' => 'home', 'fr' => 'foyer', 'it' => 'casa'),
    );
}

/** Feelings and sensations. */
function pvc_lt_offline_feelings(): array {
    return array(
        'feliz' => array('en' => 'happy', 'fr' => 'heureuse', 'it' => 'felice'),
        'contenta' => array('en' => 'glad', 'fr' => 'contente', 'it' => 'contenta'),
        'ilusionada' => array('en' => 'excited', 'fr' => 'enthousiaste', 'it' => 'entusiasta'),
        'emocionada' => array('en' => 'moved', 'fr' => 'émue', 'it' => 'emozionata'),
        'relajada' => array('en' => 'relaxed', 'fr' => 'détendue', 'it' => 'rilassata'),
        'tranquilidad' => array('en' => 'calm', 'fr' => 'tranquillité', 'it' => 'tranquillità'),
        'confianza' => array('en' => 'trust', 'fr' => 'confiance', 'it' => 'fiducia'),
        'respeto' => array('en' => 'respect', 'fr' => 'respect', 'it' => 'rispetto'),
        'cariño' => array('en' => 'affection', 'fr' => 'tendresse', 'it' => 'affetto'),
        'amor' => array('en' => 'love', 'fr' => 'amour', 'it' => 'amore'),
        'atracción' => array('en' => 'attraction', 'fr' => 'attirance', 'it' => 'attrazione'),
        'tentación' => array('en' => 'temptation', 'fr' => 'tentation', 'it' => 'tentazione'),
        'intimidad' => array('en' => 'intimacy', 'fr' => 'intimité', 'it' => 'intimità'),
        'comodidad' => array('en' => 'comfort', 'fr' => 'confort', 'it' => 'comfort'),
        'bienestar' => array('en' => 'wellbeing', 'fr' => 'bien-être', 'it' => 'benessere'),
        'sorpresa' => array('en' => 'surprise', 'fr' => 'surprise', 'it' => 'sorpresa'),
        'aventura' => array('en' => 'adventure', 'fr' => 'aventure', 'it' => 'avventura'),
        'recuerdo' => array('en' => 'memory', 'fr' => 'souvenir', 'it' => 'ricordo'),
        'momento' => array('en' => 'moment', 'fr' => 'moment', 'it' => 'momento'),
        'instante' => array('en' => 'instant', 'fr' => 'instant', 'it' => 'istante'),
    );
}

/** Connectors, time and everyday words. */
function pvc_lt_offline_common(): array {
    return array(
        'y' => array('en' => 'and', 'fr' => 'et', 'it' => 'e'),
        'o' => array('en' => 'or', 'fr' => 'ou', 'it' => 'o'),
        'pero' => array('en' => 'but', 'fr' => 'mais', 'it' => 'ma'),
        'con' => array('en' => 'with', 'fr' => 'avec', 'it' => 'con'),
        'sin' => array('en' => 'without', 'fr' => 'sans', 'it' => 'senza'),
        'para' => array('en' => 'for', 'fr' => 'pour', 'it' => 'per'),
        'por' => array('en' => 'by', 'fr' => 'par', 'it' => 'da'),
        'en' => array('en' => 'in', 'fr' => 'à', 'it' => 'a'),
        'muy' => array('en' => 'very', 'fr' => 'très', 'it' => 'molto'),
        'más' => array('en' => 'more', 'fr' => 'plus', 'it' => 'più'),
        'menos' => array('en' => 'less', 'fr' => 'moins', 'it' => 'meno'),
        'también' => array('en' => 'also', 'fr' => 'aussi', 'it' => 'anche'),
        'siempre' => array('en' => 'always', 'fr' => 'toujours', 'it' => 'sempre'),
        'nunca' => array('en' => 'never', 'fr' => 'jamais', 'it' => 'mai'),
        'ahora' => array('en' => 'now', 'fr' => 'maintenant', 'it' => 'adesso'),
        'hoy' => array('en' => 'today', 'fr' => 'aujourd’hui', 'it' => 'oggi'),
        'mañana' => array('en' => 'tomorrow', 'fr' => 'demain', 'it' => 'domani'),
        'ayer' => array('en' => 'yesterday', 'fr' => 'hier', 'it' => 'ieri'),
        'todo' => array('en' => 'everything', 'fr' => 'tout', 'it' => 'tutto'),
        'todo el día' => array('en' => 'all day', 'fr' => 'toute la journée', 'it' => 'tutto il giorno'),
        'nueva' => array('en' => 'new', 'fr' => 'nouvelle', 'it' => 'nuova'),
        'nuevo' => array('en' => 'new', 'fr' => 'nouveau', 'it' => 'nuovo'),
        'disponible' => array('en' => 'available', 'fr' => 'disponible', 'it' => 'disponibile'),
        'no disponible' => array('en' => 'unavailable', 'fr' => 'indisponible', 'it' => 'non disponibile'),
        'bajo consulta' => array('en' => 'on request', 'fr' => 'sur demande', 'it' => 'su richiesta'),
        'limitada' => array('en' => 'limited', 'fr' => 'limitée', 'it' => 'limitata'),
        'limitado' => array('en' => 'limited', 'fr' => 'limité', 'it' => 'limitato'),
        'agotada' => array('en' => 'sold out', 'fr' => 'complète', 'it' => 'esaurita'),
        'primera vez' => array('en' => 'first time', 'fr' => 'première fois', 'it' => 'prima volta'),
        'a domicilio' => array('en' => 'at home', 'fr' => 'à domicile', 'it' => 'a domicilio'),
        'en hotel' => array('en' => 'at the hotel', 'fr' => 'à l’hôtel', 'it' => 'in hotel'),
        'a tu casa' => array('en' => 'to your place', 'fr' => 'chez vous', 'it' => 'a casa tua'),
        'cerca de' => array('en' => 'near', 'fr' => 'près de', 'it' => 'vicino a'),
        'discretamente' => array('en' => 'discreetly', 'fr' => 'discrètement', 'it' => 'discretamente'),
        'exclusivamente' => array('en' => 'exclusively', 'fr' => 'exclusivement', 'it' => 'esclusivamente'),
        'solo' => array('en' => 'only', 'fr' => 'seulement', 'it' => 'solo'),
        'también disponible' => array('en' => 'also available', 'fr' => 'également disponible', 'it' => 'disponibile anche'),
        'por horas' => array('en' => 'by the hour', 'fr' => 'à l’heure', 'it' => 'a ore'),
        'sin prisa' => array('en' => 'without rushing', 'fr' => 'sans se presser', 'it' => 'senza fretta'),
        'con calma' => array('en' => 'unhurried', 'fr' => 'tranquillement', 'it' => 'con calma'),
        'de lujo' => array('en' => 'luxury', 'fr' => 'de luxe', 'it' => 'di lusso'),
        'de ensueño' => array('en' => 'dreamlike', 'fr' => 'de rêve', 'it' => 'da sogno'),
    );
}

/** Spoken languages, stored lowercase so the source capitalisation is copied over. */
function pvc_lt_offline_languages(): array {
    return array(
        'inglés' => array('en' => 'english', 'fr' => 'anglais', 'it' => 'inglese'),
        'español' => array('en' => 'spanish', 'fr' => 'espagnol', 'it' => 'spagnolo'),
        'italiano' => array('en' => 'italian', 'fr' => 'italien', 'it' => 'italiano'),
        'francés' => array('en' => 'french', 'fr' => 'français', 'it' => 'francese'),
        'alemán' => array('en' => 'german', 'fr' => 'allemand', 'it' => 'tedesco'),
        'portugués' => array('en' => 'portuguese', 'fr' => 'portugais', 'it' => 'portoghese'),
        'catalán' => array('en' => 'catalan', 'fr' => 'catalan', 'it' => 'catalano'),
        'ruso' => array('en' => 'russian', 'fr' => 'russe', 'it' => 'russo'),
        'árabe' => array('en' => 'arabic', 'fr' => 'arabe', 'it' => 'arabo'),
        'chino' => array('en' => 'chinese', 'fr' => 'chinois', 'it' => 'cinese'),
        'japonés' => array('en' => 'japanese', 'fr' => 'japonais', 'it' => 'giapponese'),
        'griego' => array('en' => 'greek', 'fr' => 'grec', 'it' => 'greco'),
        'holandés' => array('en' => 'dutch', 'fr' => 'néerlandais', 'it' => 'olandese'),
        'sueco' => array('en' => 'swedish', 'fr' => 'suédois', 'it' => 'svedese'),
        'noruego' => array('en' => 'norwegian', 'fr' => 'norvégien', 'it' => 'norvegese'),
        'danés' => array('en' => 'danish', 'fr' => 'danois', 'it' => 'danese'),
        'polaco' => array('en' => 'polish', 'fr' => 'polonais', 'it' => 'polacco'),
        'rumano' => array('en' => 'romanian', 'fr' => 'roumain', 'it' => 'rumeno'),
        'húngaro' => array('en' => 'hungarian', 'fr' => 'hongrois', 'it' => 'ungherese'),
        'turco' => array('en' => 'turkish', 'fr' => 'turc', 'it' => 'turco'),
        'hebreo' => array('en' => 'hebrew', 'fr' => 'hébreu', 'it' => 'ebraico'),
        'hindi' => array('en' => 'hindi', 'fr' => 'hindi', 'it' => 'hindi'),
        'coreano' => array('en' => 'korean', 'fr' => 'coréen', 'it' => 'coreano'),
        'ucraniano' => array('en' => 'ukrainian', 'fr' => 'ukrainien', 'it' => 'ucraino'),
    );
}
