/**
 * Editable copy for the contact buttons and the Spanish legal mechanics.
 *
 * These strings are import defaults only: every value can be edited afterwards in
 * WordPress under "Textos y diseño" (secciones "Botones de contacto" y "Legal y
 * cookies") without rebuilding the theme. They are not legal advice and are published
 * as a template until the responsible party approves the provider data.
 *
 * Flat keys are used on purpose: the copy editor stores dotted paths, so arrays would
 * not round-trip. See `pvc_set_nested()` in the content plugin.
 */
import type { Locale } from '../../lib/i18n/locales';

export const contactCopy = {
  es: {
    eyebrow: 'Contacto directo',
    title: 'Habla con nosotros',
    lead: 'Elige el canal que prefieras. La atención es discreta y se responde lo antes posible dentro del horario de servicio.',
    groupAria: 'Canales de contacto disponibles',
    channels: { whatsapp: 'WhatsApp', telegram: 'Telegram', phone: 'Llamar', email: 'Escribir un correo', form: 'Formulario de contacto', report: 'Reportar contenido' },
    disabledTitle: 'Contacto desactivado',
    disabledBody: 'Todavía no hay un canal de contacto aprobado. Cuando el responsable lo autorice, aquí aparecerán los botones activos.',
    disabledButton: 'Contactar · no disponible',
    safetyTitle: 'Antes de escribir',
    safetyItem1: 'Servicio exclusivo para personas adultas.',
    safetyItem2: 'No se atienden solicitudes de menores de edad ni de contenido ilegal.',
    safetyItem3: 'No envíes datos personales por canales no aprobados.',
    privacyNote: 'Al usar un canal de contacto se tratarán los datos que facilites con la única finalidad de atender tu solicitud.',
    responseNote: 'Disponibilidad orientativa. La confirmación se realiza siempre por el canal aprobado.',
  },
  en: {
    eyebrow: 'Direct contact',
    title: 'Talk to us',
    lead: 'Choose the channel you prefer. Assistance is discreet and answered as soon as possible within service hours.',
    groupAria: 'Available contact channels',
    channels: { whatsapp: 'WhatsApp', telegram: 'Telegram', phone: 'Call', email: 'Send an email', form: 'Contact form', report: 'Report content' },
    disabledTitle: 'Contact disabled',
    disabledBody: 'There is no approved contact channel yet. Once the responsible party authorises it, the active buttons will appear here.',
    disabledButton: 'Contact · unavailable',
    safetyTitle: 'Before writing',
    safetyItem1: 'Adults-only service.',
    safetyItem2: 'Requests from minors or for illegal content are not accepted.',
    safetyItem3: 'Do not send personal data through unapproved channels.',
    privacyNote: 'Using a contact channel means the data you provide is processed solely in order to answer your request.',
    responseNote: 'Indicative availability. Confirmation always happens through the approved channel.',
  },
  fr: {
    eyebrow: 'Contact direct',
    title: 'Parlez-nous',
    lead: 'Choisissez le canal que vous préférez. L’accueil est discret et la réponse intervient dès que possible pendant les heures de service.',
    groupAria: 'Canaux de contact disponibles',
    channels: { whatsapp: 'WhatsApp', telegram: 'Telegram', phone: 'Appeler', email: 'Envoyer un e-mail', form: 'Formulaire de contact', report: 'Signaler un contenu' },
    disabledTitle: 'Contact désactivé',
    disabledBody: 'Aucun canal de contact approuvé pour le moment. Dès que le responsable l’autorisera, les boutons actifs apparaîtront ici.',
    disabledButton: 'Contacter · indisponible',
    safetyTitle: 'Avant d’écrire',
    safetyItem1: 'Service réservé aux personnes majeures.',
    safetyItem2: 'Les demandes de mineurs ou de contenu illégal ne sont pas acceptées.',
    safetyItem3: 'N’envoyez pas de données personnelles par des canaux non approuvés.',
    privacyNote: 'L’utilisation d’un canal de contact implique que les données fournies sont traitées dans le seul but de répondre à votre demande.',
    responseNote: 'Disponibilité indicative. La confirmation s’effectue toujours par le canal approuvé.',
  },
  it: {
    eyebrow: 'Contatto diretto',
    title: 'Parla con noi',
    lead: 'Scegli il canale che preferisci. L’assistenza è discreta e risponde il prima possibile durante l’orario di servizio.',
    groupAria: 'Canali di contatto disponibili',
    channels: { whatsapp: 'WhatsApp', telegram: 'Telegram', phone: 'Chiama', email: 'Invia un’e-mail', form: 'Modulo di contatto', report: 'Segnala un contenuto' },
    disabledTitle: 'Contatto disattivato',
    disabledBody: 'Non c’è ancora un canale di contatto approvato. Quando il responsabile lo autorizzerà, qui compariranno i pulsanti attivi.',
    disabledButton: 'Contatta · non disponibile',
    safetyTitle: 'Prima di scrivere',
    safetyItem1: 'Servizio riservato a persone adulte.',
    safetyItem2: 'Non si accettano richieste di minorenni o di contenuti illegali.',
    safetyItem3: 'Non inviare dati personali tramite canali non approvati.',
    privacyNote: 'Usando un canale di contatto, i dati forniti saranno trattati al solo fine di rispondere alla tua richiesta.',
    responseNote: 'Disponibilità indicativa. La conferma avviene sempre tramite il canale approvato.',
  },
} as const satisfies Readonly<Record<Locale, unknown>>;

/**
 * Labels for the profile attributes grid and the booking button.
 *
 * They used to be written into the template as per-locale ternaries, which meant the panel could
 * not edit them and a language could not be corrected without a release. They are copy now, like
 * every other public string.
 */
export const profileFieldsCopy = {
  es: { age: 'Edad', height: 'Estatura', city: 'Ciudad', availability: 'Disponibilidad', tags: 'Detalles e idiomas', reserve: 'Reservar' },
  en: { age: 'Age', height: 'Height', city: 'City', availability: 'Availability', tags: 'Details and languages', reserve: 'Book' },
  fr: { age: 'Âge', height: 'Taille', city: 'Ville', availability: 'Disponibilité', tags: 'Détails et langues', reserve: 'Réserver' },
  it: { age: 'Età', height: 'Altezza', city: 'Città', availability: 'Disponibilità', tags: 'Dettagli e lingue', reserve: 'Prenota' },
};

/**
 * Discretion block published on every profile.
 *
 * It is written for this business specifically: the site has no premises, so everything happens
 * on an outcall to a hotel or a home. Nothing here promises a venue, a licence, a length of
 * service or a price, and there is no borrowed claim about how long anybody has been trading.
 */
export const discretionCopy = {
  es: {
    eyebrow: 'Discreción y privacidad',
    title: 'Tu privacidad no se negocia',
    body1: 'La discreción no es un extra: es la base de todo lo que hacemos. Cada encuentro se organiza de forma privada, sin nombres, sin registros innecesarios y sin rastro en tu entorno. Acordamos contigo el lugar y el momento, y la acompañante llega sola, sin llamar la atención ni identificarse ante nadie.',
    body2: 'Si es tu primera vez, no vas a tener que improvisar nada: hablamos antes, resolvemos tus dudas y decidimos juntos cómo, cuándo y dónde. A partir de ahí, la experiencia es tuya y de nadie más.',
    guideCta: 'Lee nuestra guía',
  },
  en: {
    eyebrow: 'Discretion and privacy',
    title: 'Your privacy is not negotiable',
    body1: 'Discretion is not an extra: it is the basis of everything we do. Every meeting is arranged privately, with no names, no unnecessary records and no trace in your surroundings. We agree the place and the time with you, and the companion arrives alone, drawing no attention and identifying herself to no one.',
    body2: 'If this is your first time, you will not have to improvise anything: we talk first, answer your questions and settle together how, when and where. From there on, the experience is yours and no one else’s.',
    guideCta: 'Read our guide',
  },
  fr: {
    eyebrow: 'Discrétion et vie privée',
    title: 'Votre vie privée ne se négocie pas',
    body1: 'La discrétion n’est pas un supplément : c’est la base de tout ce que nous faisons. Chaque rencontre s’organise en privé, sans noms, sans registres inutiles et sans trace dans votre entourage. Nous convenons avec vous du lieu et du moment, et l’accompagnante arrive seule, sans attirer l’attention et sans se présenter à quiconque.',
    body2: 'Si c’est votre première fois, vous n’aurez rien à improviser : on parle d’abord, on répond à vos questions et on décide ensemble comment, quand et où. Ensuite, l’expérience est la vôtre et celle de personne d’autre.',
    guideCta: 'Lisez notre guide',
  },
  it: {
    eyebrow: 'Discrezione e privacy',
    title: 'La tua privacy non si negozia',
    body1: 'La discrezione non è un extra: è la base di tutto ciò che facciamo. Ogni incontro si organizza in privato, senza nomi, senza registri inutili e senza tracce nel tuo ambiente. Concordiamo con te il luogo e il momento, e l’accompagnatrice arriva da sola, senza attirare l’attenzione e senza presentarsi a nessuno.',
    body2: 'Se è la tua prima volta, non dovrai improvvisare nulla: prima si parla, si risolvono i dubbi e si decide insieme come, quando e dove. Da lì in poi l’esperienza è tua e di nessun altro.',
    guideCta: 'Leggi la nostra guida',
  },
};

export const legalCopy = {
  es: {
    eyebrow: 'Información legal',
    updatedLabel: 'Última actualización: {date}',
    versionLabel: 'Versión {version}',
    pendingTitle: 'Documento pendiente de aprobación',
    pendingBody: 'Este documento es una plantilla editable. No se publica como texto legal definitivo hasta que el responsable jurídico complete los datos del prestador y apruebe el contenido.',
    pendingMissing: 'Faltan {count} datos obligatorios del prestador.',
    identificationTitle: 'Identificación del prestador',
    identificationBody: 'Información facilitada de forma permanente, fácil, directa y gratuita conforme al artículo 10 de la Ley 34/2002 (LSSI).',
    provider: {
      name: 'Denominación social', taxId: 'NIF / CIF', address: 'Domicilio', email: 'Correo de contacto',
      tradeName: 'Nombre comercial', phone: 'Teléfono', registry: 'Datos registrales',
      domainOwner: 'Titular del dominio', approver: 'Responsable jurídico que aprueba',
    },
    layersTitle: 'Información por capas',
    layersIntro: 'Primero el resumen y después el detalle, con acceso permanente al documento completo.',
    layersSummary: 'Resumen',
    layersDetail: 'Detalle',
    layersRights: 'Derechos',
    layersRightsBody: 'Puedes solicitar acceso, rectificación, supresión, oposición, limitación y portabilidad por el correo indicado en la identificación del prestador. También puedes reclamar ante la Agencia Española de Protección de Datos.',
    layersPending: 'El detalle del tratamiento por finalidades debe completarlo y aprobarlo el responsable.',
    cookies: {
      title: 'Cookies y almacenamiento local',
      intro: 'Aquí puedes consultar qué cookies y almacenamiento local usa este sitio y cambiar tu decisión en cualquier momento.',
      essential: 'Necesarias',
      none: 'Este sitio no utiliza cookies no esenciales, así que no se solicita consentimiento para ninguna finalidad opcional.',
      inventoryTitle: 'Inventario',
      inventoryPending: 'El inventario todavía no está completo ni aprobado. Debe revisarlo el responsable legal.',
      column1: 'Nombre', column2: 'Proveedor', column3: 'Finalidad', column4: 'Duración', column5: 'Categoría',
      analyticsTitle: 'Analítica',
      analyticsNone: 'No hay ningún proveedor de analítica activo.',
      analyticsInfo: 'Proveedor previsto: {provider}. Conservación: {retention}. Región: {region}.',
      accept: 'Aceptar todo',
      reject: 'Rechazar todo',
      configure: 'Configurar',
      save: 'Guardar mi decisión',
      revoke: 'Cambiar mi decisión',
      revoked: 'Tu decisión se ha guardado en este navegador.',
      reviewNeeded: 'La política de cookies ha cambiado. Revisa de nuevo tu decisión.',
      categories: { essential: 'Necesarias', analytics: 'Analítica', marketing: 'Publicidad' },
    },
    age: {
      title: 'Acceso exclusivo para mayores de 18 años',
      shellBody: 'Antes de acceder al contenido es necesario comprobar que tienes 18 años o más.',
      unavailable: 'La verificación de edad todavía no está disponible. El contenido permanece cerrado.',
      exit: 'Salir',
      privacy: 'No envíes documentos de identidad, fotografías ni tu fecha de nacimiento por esta página. La comprobación la realiza un proveedor autorizado y este sitio solo recibe el resultado.',
      legal: 'Información legal',
    },
    report: {
      title: 'Canal de reporte y reclamaciones',
      body: 'Para comunicar contenido usado sin permiso, suplantación de identidad, material de menores, explotación, coacción o vulneración de derechos de datos.',
      pending: 'El canal de reporte todavía no está aprobado. Debe facilitarse un destino real y atendido antes de publicar el sitio.',
      notice: 'No envíes documentos de identidad ni imágenes íntimas por este canal. Indica la dirección del contenido y el motivo.',
    },
    documents: {
      'aviso-legal': { title: 'Aviso legal', intro: 'Titularidad, condiciones de acceso y responsabilidad sobre este sitio.' },
      privacidad: { title: 'Política de privacidad', intro: 'Responsable, finalidades, base jurídica, conservación y derechos.' },
      cookies: { title: 'Política de cookies', intro: 'Inventario, finalidad, duración y gestión de tus decisiones.' },
      'terminos-del-servicio': { title: 'Términos y condiciones', intro: 'Descripción del servicio, consulta, disponibilidad y reclamaciones.' },
    },
  },
  en: {
    eyebrow: 'Legal information',
    updatedLabel: 'Last updated: {date}',
    versionLabel: 'Version {version}',
    pendingTitle: 'Document pending approval',
    pendingBody: 'This document is an editable template. It is not published as final legal text until the responsible party completes the provider data and approves the content.',
    pendingMissing: '{count} mandatory provider details are still missing.',
    identificationTitle: 'Provider identification',
    identificationBody: 'Information provided permanently, easily, directly and free of charge under article 10 of Spanish Law 34/2002 (LSSI).',
    provider: {
      name: 'Company name', taxId: 'Tax identifier', address: 'Registered address', email: 'Contact email',
      tradeName: 'Trade name', phone: 'Telephone', registry: 'Registry details',
      domainOwner: 'Domain owner', approver: 'Legal officer approving publication',
    },
    layersTitle: 'Layered information',
    layersIntro: 'A summary first and the detail afterwards, with permanent access to the full document.',
    layersSummary: 'Summary',
    layersDetail: 'Detail',
    layersRights: 'Rights',
    layersRightsBody: 'You may request access, rectification, erasure, objection, restriction and portability using the email shown in the provider identification. You may also lodge a complaint with the Spanish Data Protection Agency.',
    layersPending: 'The processing detail per purpose must be completed and approved by the responsible party.',
    cookies: {
      title: 'Cookies and local storage',
      intro: 'Here you can review which cookies and local storage this site uses and change your decision at any time.',
      essential: 'Necessary',
      none: 'This site does not use non-essential cookies, so no consent is requested for any optional purpose.',
      inventoryTitle: 'Inventory',
      inventoryPending: 'The inventory is not complete or approved yet. The legal officer must review it.',
      column1: 'Name', column2: 'Provider', column3: 'Purpose', column4: 'Duration', column5: 'Category',
      analyticsTitle: 'Analytics',
      analyticsNone: 'No analytics provider is active.',
      analyticsInfo: 'Planned provider: {provider}. Retention: {retention}. Region: {region}.',
      accept: 'Accept all',
      reject: 'Reject all',
      configure: 'Configure',
      save: 'Save my choice',
      revoke: 'Change my choice',
      revoked: 'Your choice has been saved in this browser.',
      reviewNeeded: 'The cookie policy has changed. Please review your choice again.',
      categories: { essential: 'Necessary', analytics: 'Analytics', marketing: 'Advertising' },
    },
    age: {
      title: 'Access restricted to adults aged 18 or over',
      shellBody: 'Before accessing the content, your age must be checked to confirm that you are at least 18.',
      unavailable: 'Age verification is not available yet. The content remains closed.',
      exit: 'Leave',
      privacy: 'Do not send identity documents, photographs or your date of birth through this page. The check is performed by an authorised provider and this site only receives the result.',
      legal: 'Legal information',
    },
    report: {
      title: 'Reporting and complaints channel',
      body: 'To report content used without permission, impersonation, material involving minors, exploitation, coercion or data-protection breaches.',
      pending: 'The reporting channel is not approved yet. A real, attended destination must be provided before the site is published.',
      notice: 'Do not send identity documents or intimate images through this channel. State the content address and the reason.',
    },
    documents: {
      'aviso-legal': { title: 'Legal notice', intro: 'Ownership, access conditions and liability for this site.' },
      privacidad: { title: 'Privacy policy', intro: 'Controller, purposes, legal basis, retention and rights.' },
      cookies: { title: 'Cookie policy', intro: 'Inventory, purpose, duration and how to manage your choices.' },
      'terminos-del-servicio': { title: 'Terms and conditions', intro: 'Service description, enquiries, availability and complaints.' },
    },
  },
  fr: {
    eyebrow: 'Informations légales',
    updatedLabel: 'Dernière mise à jour : {date}',
    versionLabel: 'Version {version}',
    pendingTitle: 'Document en attente d’approbation',
    pendingBody: 'Ce document est un modèle modifiable. Il n’est pas publié comme texte juridique définitif tant que le responsable n’a pas complété les données du prestataire et approuvé le contenu.',
    pendingMissing: 'Il manque {count} données obligatoires du prestataire.',
    identificationTitle: 'Identification du prestataire',
    identificationBody: 'Informations fournies de manière permanente, facile, directe et gratuite conformément à l’article 10 de la loi espagnole 34/2002 (LSSI).',
    provider: {
      name: 'Dénomination sociale', taxId: 'NIF / CIF', address: 'Adresse', email: 'E-mail de contact',
      tradeName: 'Nom commercial', phone: 'Téléphone', registry: 'Données d’immatriculation',
      domainOwner: 'Titulaire du domaine', approver: 'Responsable juridique qui approuve',
    },
    layersTitle: 'Information par couches',
    layersIntro: 'D’abord le résumé, ensuite le détail, avec un accès permanent au document complet.',
    layersSummary: 'Résumé',
    layersDetail: 'Détail',
    layersRights: 'Droits',
    layersRightsBody: 'Vous pouvez demander l’accès, la rectification, l’effacement, l’opposition, la limitation et la portabilité à l’adresse indiquée dans l’identification du prestataire. Vous pouvez également saisir l’Agence espagnole de protection des données.',
    layersPending: 'Le détail des traitements par finalité doit être complété et approuvé par le responsable.',
    cookies: {
      title: 'Cookies et stockage local',
      intro: 'Vous pouvez consulter ici les cookies et le stockage local utilisés par ce site et modifier votre choix à tout moment.',
      essential: 'Nécessaires',
      none: 'Ce site n’utilise pas de cookies non essentiels ; aucun consentement n’est donc demandé pour une finalité optionnelle.',
      inventoryTitle: 'Inventaire',
      inventoryPending: 'L’inventaire n’est pas encore complet ni approuvé. Le responsable juridique doit le vérifier.',
      column1: 'Nom', column2: 'Fournisseur', column3: 'Finalité', column4: 'Durée', column5: 'Catégorie',
      analyticsTitle: 'Analytique',
      analyticsNone: 'Aucun fournisseur d’analytique n’est actif.',
      analyticsInfo: 'Fournisseur prévu : {provider}. Conservation : {retention}. Région : {region}.',
      accept: 'Tout accepter',
      reject: 'Tout refuser',
      configure: 'Configurer',
      save: 'Enregistrer mon choix',
      revoke: 'Modifier mon choix',
      revoked: 'Votre choix a été enregistré dans ce navigateur.',
      reviewNeeded: 'La politique de cookies a changé. Veuillez revoir votre choix.',
      categories: { essential: 'Nécessaires', analytics: 'Analytique', marketing: 'Publicité' },
    },
    age: {
      title: 'Accès réservé aux personnes de 18 ans et plus',
      shellBody: 'Avant d’accéder au contenu, votre âge doit être vérifié pour confirmer que vous avez au moins 18 ans.',
      unavailable: 'La vérification de l’âge n’est pas encore disponible. Le contenu reste inaccessible.',
      exit: 'Quitter',
      privacy: 'N’envoyez pas de pièce d’identité, de photographie ou de date de naissance sur cette page. La vérification est réalisée par un prestataire autorisé et ce site ne reçoit que le résultat.',
      legal: 'Informations légales',
    },
    report: {
      title: 'Canal de signalement et de réclamation',
      body: 'Pour signaler un contenu utilisé sans autorisation, une usurpation d’identité, un contenu impliquant des mineurs, une exploitation, une contrainte ou une atteinte aux données personnelles.',
      pending: 'Le canal de signalement n’est pas encore approuvé. Une destination réelle et traitée doit être fournie avant la publication du site.',
      notice: 'N’envoyez pas de pièce d’identité ni d’image intime par ce canal. Indiquez l’adresse du contenu et le motif.',
    },
    documents: {
      'aviso-legal': { title: 'Mentions légales', intro: 'Titularité, conditions d’accès et responsabilité de ce site.' },
      privacidad: { title: 'Politique de confidentialité', intro: 'Responsable, finalités, base juridique, conservation et droits.' },
      cookies: { title: 'Politique de cookies', intro: 'Inventaire, finalité, durée et gestion de vos choix.' },
      'terminos-del-servicio': { title: 'Conditions générales', intro: 'Description du service, demandes, disponibilité et réclamations.' },
    },
  },
  it: {
    eyebrow: 'Informazioni legali',
    updatedLabel: 'Ultimo aggiornamento: {date}',
    versionLabel: 'Versione {version}',
    pendingTitle: 'Documento in attesa di approvazione',
    pendingBody: 'Questo documento è un modello modificabile. Non viene pubblicato come testo legale definitivo finché il responsabile non completa i dati del prestatore e approva il contenuto.',
    pendingMissing: 'Mancano {count} dati obbligatori del prestatore.',
    identificationTitle: 'Identificazione del prestatore',
    identificationBody: 'Informazioni fornite in modo permanente, facile, diretto e gratuito ai sensi dell’articolo 10 della legge spagnola 34/2002 (LSSI).',
    provider: {
      name: 'Denominazione sociale', taxId: 'NIF / CIF', address: 'Indirizzo', email: 'E-mail di contatto',
      tradeName: 'Nome commerciale', phone: 'Telefono', registry: 'Dati di registrazione',
      domainOwner: 'Titolare del dominio', approver: 'Responsabile legale che approva',
    },
    layersTitle: 'Informazioni per livelli',
    layersIntro: 'Prima il riepilogo e poi il dettaglio, con accesso permanente al documento completo.',
    layersSummary: 'Riepilogo',
    layersDetail: 'Dettaglio',
    layersRights: 'Diritti',
    layersRightsBody: 'Puoi richiedere accesso, rettifica, cancellazione, opposizione, limitazione e portabilità all’indirizzo indicato nell’identificazione del prestatore. Puoi anche proporre reclamo all’Agenzia spagnola per la protezione dei dati.',
    layersPending: 'Il dettaglio del trattamento per finalità deve essere completato e approvato dal responsabile.',
    cookies: {
      title: 'Cookie e archiviazione locale',
      intro: 'Qui puoi consultare quali cookie e archiviazione locale utilizza questo sito e modificare la tua scelta in qualsiasi momento.',
      essential: 'Necessari',
      none: 'Questo sito non utilizza cookie non essenziali, quindi non viene richiesto alcun consenso per finalità opzionali.',
      inventoryTitle: 'Inventario',
      inventoryPending: 'L’inventario non è ancora completo né approvato. Deve verificarlo il responsabile legale.',
      column1: 'Nome', column2: 'Fornitore', column3: 'Finalità', column4: 'Durata', column5: 'Categoria',
      analyticsTitle: 'Analytics',
      analyticsNone: 'Nessun fornitore di analytics è attivo.',
      analyticsInfo: 'Fornitore previsto: {provider}. Conservazione: {retention}. Regione: {region}.',
      accept: 'Accetta tutto',
      reject: 'Rifiuta tutto',
      configure: 'Configura',
      save: 'Salva la mia scelta',
      revoke: 'Modifica la mia scelta',
      revoked: 'La tua scelta è stata salvata in questo browser.',
      reviewNeeded: 'La politica dei cookie è cambiata. Rivedi la tua scelta.',
      categories: { essential: 'Necessari', analytics: 'Analytics', marketing: 'Pubblicità' },
    },
    age: {
      title: 'Accesso riservato a chi ha almeno 18 anni',
      shellBody: 'Prima di accedere ai contenuti è necessario verificare che tu abbia almeno 18 anni.',
      unavailable: 'La verifica dell’età non è ancora disponibile. I contenuti restano chiusi.',
      exit: 'Esci',
      privacy: 'Non inviare documenti d’identità, fotografie o la tua data di nascita tramite questa pagina. La verifica è effettuata da un fornitore autorizzato e questo sito riceve solo il risultato.',
      legal: 'Informazioni legali',
    },
    report: {
      title: 'Canale di segnalazione e reclamo',
      body: 'Per segnalare contenuti usati senza permesso, furto d’identità, materiale che coinvolge minori, sfruttamento, coercizione o violazioni dei dati personali.',
      pending: 'Il canale di segnalazione non è ancora approvato. Prima di pubblicare il sito deve essere fornita una destinazione reale e presidiata.',
      notice: 'Non inviare documenti d’identità né immagini intime tramite questo canale. Indica l’indirizzo del contenuto e il motivo.',
    },
    documents: {
      'aviso-legal': { title: 'Note legali', intro: 'Titolarità, condizioni di accesso e responsabilità di questo sito.' },
      privacidad: { title: 'Informativa sulla privacy', intro: 'Titolare, finalità, base giuridica, conservazione e diritti.' },
      cookies: { title: 'Politica sui cookie', intro: 'Inventario, finalità, durata e gestione delle tue scelte.' },
      'terminos-del-servicio': { title: 'Termini e condizioni', intro: 'Descrizione del servizio, richieste, disponibilità e reclami.' },
    },
  },
} as const satisfies Readonly<Record<Locale, unknown>>;

export function getContactCopy(locale: Locale) { return contactCopy[locale]; }
export function getDiscretionCopy(locale: Locale) { return discretionCopy[locale]; }
export function getProfileFieldsCopy(locale: Locale) { return profileFieldsCopy[locale]; }
export function getLegalCopy(locale: Locale) { return legalCopy[locale]; }
